from pathlib import Path
BASE_OUTPUT = Path.home()/ 'browser-summaries'
DAILY_DIR = BASE_OUTPUT/'daily'
WEEKLY_DIR = BASE_OUTPUT/'weekly'
OBSIDIAN_VAULT=None
OBSIDIAN_DAILY_TEMPLATE=None
DAYS_FOR_DAILY=1
DAYS_FOR_WEEKLY=7
SYNC_TO_OBSIDIAN=False
LLM_TAGGER=None
EXTERNAL_TAGGER=None
TOP_N_TOPICS=2
MAX_WEEKLY_ITEMS=1000
